### ISSUE TITLE
Isuue on publishing an article

### ISSUE THREAD

**Issue by ahmedgad-it** [pkp/sword#24]
Hi,

On publishing an article, the article is published successfully, however; an error,
> An unexpected error occurred. You may have been logged out. Please reload the page and try again.

is shown!

**Comment by asmecher** [comment]
@ahmedgad-it, is this related to the SWORD plugin?

**Comment by ahmedgad-it** [comment]
Yes, on disabling SWORD plugin, everything is woking OK.

**Comment by asmecher** [comment]
@ahmedgad-it, what do you see in the error log?

**Comment by ahmedgad-it** [comment]
[Sun May 17 11:11:50.544910 2020] [php7:warn] [pid 6180:tid 1984] [client 192.168.14.1:49492] PHP Warning:  require_once(D:\\xampp\\htdocs\\journals\\plugins\\generic\\sword\\classes/../libs/swordappv2/swordappclient.php): failed to open stream: No such file or directory in D:\\xampp\\htdocs\\journals\\plugins\\generic\\sword\\classes\\PKPSwordDeposit.inc.php on line 16, referer: http://journal.jlsh.kfs.edu.eg/index.php/jlsh/management/importexport/plugin/QuickSubmitPlugin?fbclid=IwAR25ntCzHkO_3O9C5St5GiytfTJVKGy3QIFLkrflxOpvDP0o3XmqT5wAyB8

[Sun May 17 11:11:50.544910 2020] [php7:error] [pid 6180:tid 1984] [client 192.168.14.1:49492] PHP Fatal error:  require_once(): Failed opening required 'D:\\xampp\\htdocs\\journals\\plugins\\generic\\sword\\classes/../libs/swordappv2/swordappclient.php' (include_path='D:\\xampp\\php\\PEAR') in D:\\xampp\\htdocs\\journals\\plugins\\generic\\sword\\classes\\PKPSwordDeposit.inc.php on line 16, referer:

**Comment by ahmedgad-it** [comment]
> 
> 
> @ahmedgad-it, what do you see in the error log?

[Sun May 17 11:11:50.544910 2020] [php7:warn] [pid 6180:tid 1984] [client 192.168.14.1:49492] PHP Warning: require_once(D:\xampp\htdocs\journals\plugins\generic\sword\classes/../libs/swordappv2/swordappclient.php): failed to open stream: No such file or directory in D:\xampp\htdocs\journals\plugins\generic\sword\classes\PKPSwordDeposit.inc.php on line 16, referer: 

[Sun May 17 11:11:50.544910 2020] [php7:error] [pid 6180:tid 1984] [client 192.168.14.1:49492] PHP Fatal error: require_once(): Failed opening required 'D:\xampp\htdocs\journals\plugins\generic\sword\classes/../libs/swordappv2/swordappclient.php' (include_path='D:\xampp\php\PEAR') in D:\xampp\htdocs\journals\plugins\generic\sword\classes\PKPSwordDeposit.inc.php on line 16, referer:

**Comment by asmecher** [comment]
@ahmedgad-it, how did you install the plugin?

**Comment by ahmedgad-it** [comment]
> 
> 
> @ahmedgad-it, how did you install the plugin?

Manually by copy & paste plugin folder to the plugins directory, then running the upgrade script.

**Comment by asmecher** [comment]
@ahmedgad-it, the plugin will be missing its dependencies if you install it that way. I'd suggest installing it using the Plugin Gallery, or failing that, use the plugin upload tool and give it a .tar.gz package from the git repository's "Releases" area.

**Comment by ahmedgad-it** [comment]
Oh, sorry,
I really do not remember, but if it exists in the Plugin Gallery, so i have installed it from within there.

**Comment by asmecher** [comment]
@ahmedgad-it, does the file `D:\xampp\htdocs\journals\plugins\generic\sword\libs\swordappv2\swordappclient.php` exist?

**Comment by ahmedgad-it** [comment]
> 
> 
> @ahmedgad-it, does the file `D:\xampp\htdocs\journals\plugins\generic\sword\libs\swordappv2\swordappclient.php` exist?

No, it does not exist.

**Comment by asmecher** [comment]
@ahmedgad-it, then I don't think the plugin was installed using the plugin gallery.
