### ISSUE TITLE
What is the status of this project?

### ISSUE THREAD

**Issue by tomascohen** [pkp/sword#34]
People seems to be struggling to get this plugin working on stable/supported OJS.

The latest published release only supports up to 3.2.1 and dates back to June 2021.

Can this be clarified on the README?

**Comment by asmecher** [comment]
@tomascohen, there's a release for the SWORD plugin for OJS/OCS 3.3.0-x [available here](https://github.com/pkp/sword/releases/tag/v1_0_6-0); I've just added it to the plugin gallery, which it looks like has been overlooked until now. I've also released a version of the plugin for OJS/OPS 3.4.0-x.

Next time, I'd suggest asking questions like this in our [community forum](https://forum.pkp.sfu.ca/) -- that's generally the best first place to get help. Github issues are more used for specific dev tasks.

**Comment by tomascohen** [comment]
This is great. Thank you!
